fleet/urls.py
from django.urls import path
from django.conf.urls import url
from . import views


app_name = "fleet"

urlpatterns = [
    url(r"^$", views.dashboard, name="dashboard"),
    url(r"^create/$", views.create_fleet, name="create_fleet"),
    url(r"^save/$", views.save_fleet, name="save_fleet"),
    url(r"^join/(?P<fleet_id>[0-9]+)$", views.join_fleet, name="join_fleet"),
    url(r"^details/(?P<fleet_id>[0-9]+)$", views.fleet_details, name="fleet_details"),
    url(r"^edit/(?P<fleet_id>[0-9]+)$", views.edit_fleet, name="edit_fleet"),
]

fleet/models.py
from django.db import models
from allianceauth.groupmanagement.models import AuthGroup
from datetime import datetime


class Fleet(models.Model):
    fleet_id = models.BigIntegerField(primary_key=True)
    name = models.CharField(max_length=50, default="")
    fleet_commander_id = models.BigIntegerField()
    created_at = models.DateTimeField()
    motd = models.CharField(max_length=4000)
    is_free_move = models.BooleanField()

    groups = models.ManyToManyField(
        AuthGroup,
        related_name="restricted_groups",
        help_text="Group listed here will be able to join the fleet",
    )

    class Meta:
        default_permissions = ()
        permissions = (
            ("fleet_access", "Can access this app"),
            ("manage", "Can Manage Fleets"),
        )


class FleetInformation(models.Model):
    fleet = models.ForeignKey(Fleet, on_delete=models.CASCADE)
    ship_type_name = models.CharField(max_length=100)
    count = models.IntegerField()
    date = models.DateTimeField(default=datetime.now)

    class Meta:
        default_permissions = ()

fleet/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from django.contrib.auth.decorators import login_required, permission_required
from django.template.defaulttags import register

from fleet.app_settings import avoid_cdn

from .tasks import (
    open_fleet,
    send_fleet_invitation,
    get_fleet_composition,
    get_fleet_aggregate,
)

from .models import Fleet

from esi.decorators import token_required

from allianceauth.eveonline.models import EveCharacter
from allianceauth.groupmanagement.models import AuthGroup

from bravado.exception import HTTPNotFound


@login_required()
@permission_required("fleet.fleet_access")
def dashboard(request):
    groups = request.user.groups.all()
    fleets = Fleet.objects.filter(Q(groups__group__in=groups) | Q(groups=None)).all()
    context = {
        "fleets": fleets,
        "avoid_cdn": avoid_cdn(),  # AVOID_CDN setting
    }

    if "error_edit_fleet" in request.session:
        context["error"] = request.session["error_edit_fleet"].get("error", "")
        del request.session["error_edit_fleet"]

    return render(request, "fleet/dashboard.html", context)


@login_required()
@permission_required("fleet.manage")
@token_required(
    scopes=(
        "esi-fleets.read_fleet.v1",
        "esi-fleets.write_fleet.v1",
    )
)
def create_fleet(request, token):
    if request.method == "POST":
        auth_groups = AuthGroup.objects.filter(internal=False).all()
        if "modified_fleet_data" in request.session:
            ctx = {}
            ctx["error"] = request.session["modified_fleet_data"].get("error", "")
            ctx["motd"] = request.session["modified_fleet_data"].get("motd", "")
            ctx["name"] = request.session["modified_fleet_data"].get("name", "")
            ctx["groups"] = request.session["modified_fleet_data"].get("groups", "")
            ctx["is_free_move"] = request.session["modified_fleet_data"].get(
                "free_move", ""
            )
            ctx["character_id"] = token.character_id
            ctx["auth_groups"] = auth_groups

            del request.session["modified_fleet_data"]
        else:
            ctx = {"character_id": token.character_id, "auth_groups": auth_groups}

        # AVOID_CDN setting
        ctx["avoid_cdn"] = avoid_cdn()

        return render(request, "fleet/create_fleet.html", context=ctx)
    return redirect("fleet:dashboard")


@login_required()
@permission_required("fleet.manage")
def edit_fleet(request, fleet_id):
    fleet = Fleet.objects.get(fleet_id=fleet_id)
    auth_groups = AuthGroup.objects.filter(internal=False)

    ctx = {
        "character_id": fleet.fleet_commander_id,
        "auth_groups": auth_groups,
        "fleet": fleet,
        "avoid_cdn": avoid_cdn(),  # AVOID_CDN setting
    }

    return render(request, "fleet/edit_fleet.html", context=ctx)


@login_required()
@permission_required("fleet.fleet_access")
def join_fleet(request, fleet_id):
    ctx = {}
    groups = request.user.groups.all()
    fleet = Fleet.objects.filter(
        Q(groups__group__in=groups) | Q(groups=None), fleet_id=fleet_id
    ).count()

    if fleet == 0:
        return redirect("fleet:dashboard")

    if request.method == "POST":
        character_ids = request.POST.getlist("character_ids", [])
        send_fleet_invitation.delay(character_ids, fleet_id)

        return redirect("fleet:dashboard")
    else:
        characters = (
            EveCharacter.objects.filter(character_ownership__user=request.user)
            .select_related()
            .order_by("character_name")
        )
        ctx["characters"] = characters

    # AVOID_CDN setting
    ctx["avoid_cdn"] = avoid_cdn()

    return render(request, "fleet/join_fleet.html", context=ctx)


@login_required()
@permission_required("fleet.manage")
def save_fleet(request):
    if request.method == "POST":
        free_move = request.POST.get("free_move", False)

        if free_move == "on":
            free_move = True

        motd = request.POST.get("motd", "")
        name = request.POST.get("name", "")
        groups = request.POST.getlist("groups", [])

        try:
            open_fleet(request.POST["character_id"], motd, free_move, name, groups)
        except HTTPNotFound as ex:
            if request.POST.get("origin", "") == "edit":
                # Here ccp return character not in fleet. Instead push our own message to be clearer
                request.session["error_edit_fleet"] = {
                    "error": "Fleet advert is no longer valid"
                }

                return redirect("fleet:dashboard")

            if request.POST.get("origin", "") == "create":
                request.session["modified_fleet_data"] = {
                    "error": ex.swagger_result["error"],
                    "motd": motd,
                    "name": name,
                    "free_move": free_move,
                    "groups": groups,
                }

                return redirect("fleet:create_fleet")

    return redirect("fleet:dashboard")


@login_required()
@permission_required("fleet.manage")
def fleet_details(request, fleet_id):
    fleet = get_fleet_composition(fleet_id)

    ctx = {
        "fleet": fleet,
        "avoid_cdn": avoid_cdn(),  # AVOID_CDN setting
    }

    return render(request, "fleet/fleet_details.html", context=ctx)


@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)

fleet/templates/fleet/base.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}

{% block page_title %}{% trans "fleet" %}{% endblock %}

{% block content %}
    <div class="col-lg-12">
        <br />
        <div class="col-lg-12 container">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">{% trans "Toggle navigation" %}</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{% url 'fleet:dashboard' %}">{% trans "Available Fleets" %}</a>
                    </div>
                    <ul class="nav navbar-nav navbar-right">
                        {% if perms.fleet.manage %}
                            <li> <a href="{% url 'fleet:create_fleet' %}">Create Fleet</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
            {% block fleet_block %}{% endblock %}
        </div>
    </div>
{% endblock %}

fleet/templates/fleet/bundles/multi-select-css.html
{% load static %}

{% if avoid_cdn %}
    <link rel="stylesheet" href="{% static 'fleet/libs/multi-select/0.9.12/css/multi-select.min.css' %}">
{% else %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/multi-select/0.9.12/css/multi-select.min.css">
{% endif %}

fleet/templates/fleet/bundles/slim-select-css.html
{% load static %}

{% if avoid_cdn %}
    <link rel="stylesheet" href="{% static 'fleet/libs/slim-select/1.26.0/css/slimselect.min.css' %}">
{% else %}
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slim-select/1.26.0/slimselect.min.css">
{% endif %}

fleet/templates/fleet/bundles/slim-select-js.html
{% load static %}

{% if avoid_cdn %}
    <script type="application/javascript" src="{% static 'fleet/libs/slim-select/1.26.0/js/slimselect.min.js' %}"></script>
{% else %}
    <script type="application/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/slim-select/1.26.0/slimselect.min.js"></script>
{% endif %}

fleet/templates/fleet/create_fleet.html
{% extends 'fleet/base.html' %}
{% load i18n %}
{% load humanize %}

{% block extra_css %}
    {% include 'fleet/bundles/multi-select-css.html' %}
    {% include 'fleet/bundles/slim-select-css.html' %}
{% endblock %}

{% block page_title %}{% trans "Create fleet" %}{% endblock %}

{% block fleet_block %}
    <div class="container col-sm-12">
        {% if error %}
            <div class="alert alert-danger" role="alert">{{error}}</div>
        {%endif%}
        <div class="panel panel-primary">
            <div class="panel-heading">
                Create Fleet
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <form class="form-signin" role="form" action="{% url 'fleet:save_fleet' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="character_id" id="character_id" value="{{character_id}}">
                            <input type="hidden" name="origin" id="origin" value="create">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label for="name" class="control-label">Fleet Name</label>
                                        <input type="text" class="form-control" name="name" id="name" {% if name %}value="{{name}}"{%endif%}>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label for="groups" style="margin-bottom: 0;">Select Groups</label>
                                        <span class="help-block" style="margin-top: 0; margin-bottom: 0; font-size: 10pt; font-style: italic;">Only selected groups will have access to the fleet. If no groups are selected the fleet will be available to all of the authed groups.</span>
                                        <select name="groups" id="groups" multiple>
                                            {% for group in auth_groups %}
                                                {% if groups %}
                                                    {% if group in groups %}
                                                        <option value="{{group.group_id}}" selected>{{group}}</option>
                                                    {%else%}
                                                        <option value="{{group.group_id}}" selected>{{group}}</option>
                                                    {%endif%}
                                                {%else%}
                                                    <option value="{{group.group_id}}">{{group}}</option>
                                                {%endif%}
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group" >
                                        <label for="motd" class="control-label">Fleet MOTD</label>
                                        <div>
                                            <textarea class="form-control" name="motd" id="motd" rows="10">{% if motd %}{{motd}}{%endif%}</textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <input type="checkbox" style="margin-right: 5px;" class="form-check-input" name="free_move" id="free_move" {% if is_free_move %}checked{%endif%}><label for="free_move" class="form-check-label">Enable Free Move</label>
                            <button class="btn btn-primary btn-block" type="submit">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_javascript %}
    {% include 'fleet/bundles/slim-select-js.html' %}
{% endblock %}


{% block extra_script %}

new SlimSelect({
    select: "#groups",
    hideSelectedOption: true
});

{% endblock %}

fleet/templates/fleet/dashboard.html
{% extends 'fleet/base.html' %}
{% load i18n %}
{% load humanize %}
{% load evelinks %}

{% block fleet_block %}
    <div class="container col-sm-12">
        {% if error %}
            <div class="alert alert-danger" role="alert">{{error}}</div>
        {% endif %}
        <h2>
            Available Fleets
        </h2>
        <div class="panel panel-default">
            <div class="panel-body">
                <table class="table table-hover">
                    <thead>
                        <th></th>
                        <th>Name</th>
                        <th>Created At</th>
                        <th>Join</th>
                        {% if perms.fleet.manage %}
                            <th>Details</th>
                        {% endif %}
                        {% if perms.fleet.manage %}
                            <th>Edit</th>
                        {% endif %}
                    </thead>
                    <tbody>
                        {% for fleet in fleets %}
                        <tr>
                            <td>
                                <img class="img-circle eve-character-portrait" style="display: block; margin: auto;" src="{{ fleet.fleet_commander_id|character_portrait_url:64 }}">
                            </td>
                            <td>
                                {{fleet.name}}
                            </td>
                            <td>
                                {{fleet.created_at}}
                            </td>
                            <td>
                                <a href="{% url 'fleet:join_fleet' fleet.fleet_id %}" class="btn btn-xs btn-success">Join Fleet</a>
                            </td>
                            {% if perms.fleet.manage %}
                            <td>
                                <a href="{% url 'fleet:fleet_details' fleet.fleet_id %}"  class="btn btn-xs btn-success">View fleet details</a>
                            </td>
                            {% endif %}
                            {% if perms.fleet.manage %}
                            <td>
                                <a href="{% url 'fleet:edit_fleet' fleet.fleet_id %}"  class="btn btn-xs btn-success">Edit Fleet advert</a>
                            </td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

fleet/templates/fleet/edit_fleet.html
{% extends 'fleet/base.html' %}
{% load i18n %}
{% load humanize %}

{% block extra_css %}
    {% include 'fleet/bundles/multi-select-css.html' %}
    {% include 'fleet/bundles/slim-select-css.html' %}
{% endblock %}

{% block page_title %}{% trans "Edit Fleet" %}{% endblock %}

{% block fleet_block %}
    <div class="container col-sm-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Edit Fleet
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <form class="form-signin" role="form" action="{% url 'fleet:save_fleet' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="character_id" id="character_id" value="{{character_id}}">
                            <input type="hidden" name="origin" id="origin" value="edit"/>
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label for="name" class="control-label">Fleet Name</label>
                                        <input type="text" class="form-control" name="name" id="name" value="{{fleet.name}}">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label for="groups" style="margin-bottom: 0;">Select Groups</label>
                                        <span class="help-block" style="margin-top: 0; margin-bottom: 0; font-size: 10pt; font-style: italic;">Only selected groups will have access to the fleet. If no groups are selected the fleet will be available to all of the authed groups.</span>
                                        <select name="groups" id="groups" multiple>
                                            {% for group in auth_groups %}
                                                {% if group in fleet.groups.all %}
                                                    <option value="{{group.group_id}}" selected>{{group}}</option>
                                                {% else %}
                                                    <option value="{{group.group_id}}">{{group}}</option>
                                                {% endif %}
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group" >
                                        <label for="motd" class="control-label">Fleet MOTD</label>
                                        <div>
                                            <textarea class="form-control" name="motd" id="motd" rows="10">{{fleet.motd}}</textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% if fleet.is_free_move %}
                                <input type="checkbox" style="margin-right: 5px;" class="form-check-input" name="free_move" id="free_move" checked><label for="free_move" class="form-check-label">Enable Free Move</label>
                            {% else %}
                                <input type="checkbox" style="margin-right: 5px;" class="form-check-input" name="free_move" id="free_move"><label for="free_move" class="form-check-label">Enable Free Move</label>
                            {% endif %}
                            <button class="btn btn-primary btn-block" type="submit">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_javascript %}
    {% include 'fleet/bundles/slim-select-js.html' %}
{% endblock %}


{% block extra_script %}

new SlimSelect({
    select: "#groups",
    hideSelectedOption: true
});

{% endblock %}

fleet/templates/fleet/fleet_details.html
{% extends 'fleet/base.html' %}
{% load i18n %}
{% load humanize %}
{% load evelinks %}

{% block page_title %}{% trans "Create fleet" %}{% endblock %}

{% block fleet_block %}
    <div class="container col-sm-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Fleet View
            </div>

            <div class="panel-body">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <table class="table table-hover">
                            <thead>
                                <th>Ship Name</th>
                                <th>Quantity</th>
                                <th>Since Last Update</th>
                            </thead>

                            <tbody>
                                {% for key, value in fleet.aggregate.items %}
                                <tr>
                                    <td>
                                       {{ key }}
                                    </td>
                                    <td>
                                        {{ value }}
                                    </td>
                                    <td>
                                        {{ fleet.differential|get_item:key }}
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="panel panel-primary">
            <div class="panel-heading">
                Fleet Members
            </div>

            <div class="panel-body">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <table class="table table-hover dataTable" id="docTable">
                            <thead>
                                <th>Name</th>
                                <th>Ship type</th>
                                <th>System</th>
                            </thead>

                            <tbody>
                                <tr>
                                {% for member in fleet.fleet %}
                                    <td>
                                        <img class="img-circle eve-character-portrait" src="{{ member.character_id|character_portrait_url:32 }}" style="margin-right: 1rem;"> {{member.character_name}}
                                    </td>
                                    <td>
                                        <img class="img-circle eve-type-icon" src="{{ member.ship_type_id|type_icon_url:32 }}" style="margin-right: 1rem;"> {{member.ship_type_name}}
                                    </td>
                                    <td>
                                        {{member.solar_system_name}}
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}


{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}
{% endblock %}

{% block extra_script %}
    $(document).ready(function(){
        $('#docTable').DataTable();
        $('[data-toggle="tooltip"]').tooltip();
    })

    setTimeout(function() {
        location.reload();
    }, 60000);
{% endblock %}

fleet/templates/fleet/join_fleet.html
{% extends 'fleet/base.html' %}
{% load i18n %}
{% load humanize %}

{% block page_title %}{% trans "Create fleet" %}{% endblock %}

{% block extra_css %}
    {% include 'fleet/bundles/multi-select-css.html' %}
    {% include 'fleet/bundles/slim-select-css.html' %}
{% endblock %}

{% block fleet_block %}
    <div class="container col-sm-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Fleet invitation
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <form class="form-signin" role="form" action="" method="POST">
                            {% csrf_token %}
                            </br>
                            <label for="character_ids">Select the characters to invite</label>
                            <select class="multiselect-ui" multiple="multiple" name="character_ids" id="character_ids">
                             {% for character in characters %}
                                <option value="{{character.character_id}}" >{{character.character_name}}</option>
                             {% endfor %}
                            </select>
                            </br>
                            <button class="btn btn-primary btn-block" style="margin-top: 10px;"type="submit">Send fleet invites</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_javascript %}
    {% include 'fleet/bundles/slim-select-js.html' %}
{% endblock %}


{% block extra_script %}

new SlimSelect({
    select: "#character_ids",
    hideSelectedOption: true
});

{% endblock %}